// GENERATED FILE - DO NOT EDIT.
//
// Generated by FlutterFire CLI (`flutterfire configure`) for the
// Firebase project `flutter-iti-app`. Contains the Firebase
// configuration options for each platform.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaEaA9lvf_G6Elu0mBgIRzw15qs6GFd1w',
    appId: '1:245044685:android:64a2e0c51a5eb418636084',
    messagingSenderId: '245044685',
    projectId: 'flutter-iti-app',
    storageBucket: 'flutter-iti-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7dsNhsfUVK2RYP41-vNvRuxs-CIfgx0U',
    appId: '1:245044685:ios:21a0c652d5551157636084',
    messagingSenderId: '245044685',
    projectId: 'flutter-iti-app',
    storageBucket: 'flutter-iti-app.firebasestorage.app',
    iosBundleId: 'com.example.movieVerse',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiMse6jdvPb6KkgdyhJ1aP4qPBIcwwyHM',
    appId: '1:245044685:web:3c36d9a8aec82fb5636084',
    messagingSenderId: '245044685',
    projectId: 'flutter-iti-app',
    authDomain: 'flutter-iti-app.firebaseapp.com',
    storageBucket: 'flutter-iti-app.firebasestorage.app',
    measurementId: 'G-W543L0N7W4',
  );
}
