// PLACEHOLDER: Replace this file by running `flutterfire configure`.
//
// This file is normally generated by the FlutterFire CLI. It contains the
// Firebase project configuration (project id, api key, app id, etc.).
//
// To generate the real file:
//   1. Install the firebase CLI:  npm install -g firebase-tools
//   2. Login:                     firebase login
//   3. Run from project root:     flutterfire configure
//   4. Select your Firebase project and the Android/iOS platforms.
//
// Until then, keep this placeholder so the app compiles. It intentionally
// uses an empty/invalid project so the app will not actually connect to
// Firebase until the real file is generated.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web is not supported.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // NOTE: These are placeholders. Replace by running `flutterfire configure`.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'PLACEHOLDER',
    appId: 'PLACEHOLDER',
    messagingSenderId: 'PLACEHOLDER',
    projectId: 'PLACEHOLDER',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'PLACEHOLDER',
    appId: 'PLACEHOLDER',
    messagingSenderId: 'PLACEHOLDER',
    projectId: 'PLACEHOLDER',
    iosBundleId: 'PLACEHOLDER',
  );
}
