import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import 'controllers/movie_controller.dart';
import 'firebase_options.dart';
import 'providers/auth_provider.dart';
import 'providers/favourites_provider.dart';
import 'providers/movie_details_provider.dart';
import 'providers/movie_provider.dart';
import 'services/tmdb_api_service.dart';
import 'utils/app_theme.dart';
import 'views/auth_gate.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialise Firebase before running the app. `firebase_options.dart` is
  // generated by running `flutterfire configure`.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MovieVerseApp());
}

/// The root widget of the application. It wires up all the providers
/// (Provider state management) and the theme/navigation.
class MovieVerseApp extends StatelessWidget {
  const MovieVerseApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        // Auth provider manages Firebase authentication state.
        ChangeNotifierProvider(create: (_) => AuthProvider()),
        // Movie provider owns TMDB movie/search state.
        ChangeNotifierProvider(
          create: (_) => MovieProvider(MovieController(TmdbApiService())),
        ),
        // Movie details provider fetches a single movie's full metadata/cast.
        ChangeNotifierProvider(
          create: (_) =>
              MovieDetailsProvider(MovieController(TmdbApiService())),
        ),
        // Favourites provider owns local SQFLite favourites & lists.
        ChangeNotifierProvider(create: (_) => FavouritesProvider()),
      ],
      child: MaterialApp(
        title: 'MovieVerse',
        debugShowCheckedModeBanner: false,
        theme: AppTheme.light,
        // The AuthGate decides which screen to show based on auth status.
        home: const AuthGate(),
      ),
    );
  }
}
